### ISSUE TITLE
Material UI multiple checkboxes not working properly

### ISSUE THREAD

**Issue by hbarcelos** [react-hook-form/react-hook-form-input#11]
**Describe the bug**
This is related to react-hook-form/react-hook-form#476, but with Material UI added to the equation.

I have a form for multiple choice of different themes. Users can choose 1 to 3 themes. I am using `RHFInput` to make things easier.

However, after submitting, data is always an array of booleans.

```jsx
              {AvailableThemes.map((theme, i) => (
                <FormControlLabel
                  key={theme}
                  value={theme}
                  control={
                    <RHFInput
                      as={<Checkbox />}
                      name={`themes[${i}]`}
                      type="checkbox"
                      value={theme}
                      register={register}
                      setValue={setValue}
                    />
                  }
                  label={theme}
                  className={cl.twoColumns}
                />
              ))}
```

**To Reproduce**
1. Go to the sandbox bellow
2. Check some options
3. Submit the form
4. See the console for the output data

**Codesandbox link**
https://codesandbox.io/s/material-ui-multiple-checkboxes-m6ns1

**Expected behavior**
The values in the array `themes` should be the values of the selected checkboxes, not booleans.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 70.0.1

**Comment by bluebill1049** [comment]
I will take a look at this soon :)

**Comment by hbarcelos** [comment]
I think I've found the problem here:
https://github.com/react-hook-form/react-hook-form-input/blob/master/src/index.tsx#L6

This line:
```
return target ? (isCheckbox ? target.checked : target.value) : target;
```

If we have a checkbox, it always returns the `checked` properties, regardless `value` is set or not.

To be consistent with the way `react-hook-form` works, it should return a value based on the following algorithm:

```
If `checked` is `false`:
  Then return `false`
Else if `checked` is `true`
  If `value` is non-empty
    Then return `value`
  Else
    Then return `true`
```

I've updated the linked sandbox to demonstrate this.

**Comment by bluebill1049** [comment]
you are right @hbarcelos i will adjust the code soon 👍

**Comment by bluebill1049** [comment]
actually you interested to contribute? you already know the solution :)

**Comment by hbarcelos** [comment]
Sure. How can I do that? Should I fork and submit a PR or would you give me some permissions for this repo?

**Comment by bluebill1049** [comment]
fork and submit a PR would be perfect :)

**Comment by jtoliver** [comment]
Anything new on this. I took a stab at it today with no success. I'm trying to do grouped checkboxes with same name.

**Comment by bluebill1049** [comment]
@jtoliver i believe @hbarcelos is looking into this. 
@hbarcelos any update on this PR? I am happy to take a look this over the weekend tho.

**Comment by hbarcelos** [comment]
@bluebill1049 sorry for the delay... Busy week. I'll have some time during the weekend.
It is quite an easy fix to do, but I would want to add some regression tests as well, so this could take a little bit longer than editing 1 or 2 lines.

**Comment by bluebill1049** [comment]
awesome! thanks @hbarcelos

**Comment by bluebill1049** [comment]
hey @hbarcelos, wondering if any update on this issue?

**Comment by bluebill1049** [comment]
going to close this issue for now, unless someone encounter similar problem.

**Comment by hbarcelos** [comment]
Hey, I'm sorry... This has being a pretty busy end of year for me. I'll try to work on this before x-mas though.

**Comment by bluebill1049** [comment]
ah cool! Whenever you are free man no pressure. Sorry tagged you twice 😅
