### ISSUE TITLE
Docs - Show example with a WrappedSelect (for lack of a better term)

### ISSUE THREAD

**Issue by shoeman22** [react-hook-form/react-hook-form-input#12]
When I do my Select's, I like to make them into a single component (ie: `<CountrySelect />`) and then hand that off to RHFInput's `as` property.

It took me way longer than it should've to realize I needed to also pass down props from RHFInput in order for the wrapped select to work with RHFInput.

Here's a codesandbox that shows what I'm talking about: https://codesandbox.io/s/react-hook-form-rhfinput-qifbu

Not an issue with the code at all, but it just might be helpful to include something in the docs about how this use case works as I can imagine it's a fairly common pattern to keep the finished Select somewhere else and then just basically decorate it with RHFInput.

Amazing library in general so far by the way!

**Comment by bluebill1049** [comment]
thanks for your feedback @shoeman22 i will update the example as yours :)

**Comment by bluebill1049** [comment]
```
          <section>
            <label>MUI Select (wrapped)</label>
            <RHFInput
              as={<WrappedSelect name="test" />}
              name="WrappedSelect"
              register={register}
              setValue={setValue}
            />
          </section>
```

have you try the above?

**Comment by shoeman22** [comment]
Yep, that looks like that approach would work as well for the value itself, but the other props aren't going to be sent down.

**Comment by bluebill1049** [comment]
what do you mean other props?
```
<section>
            <label>React Select</label>
            <RHFInput
              as={<ReactSelect />}
              options={options}
              name="ReactSelect"
              {...methods}
              isClearable // you can pass props here as well
            />
</section>
```

**Comment by shoeman22** [comment]
What I'd initially done was something like this:

```javascript
// alternately, it could've been thought of as:
// const WrappedSelect = (propsFromRHFInputThatWereIgnored) => (
const WrappedSelect = () => (
  <Select>
    <MenuItem value={10}>Ten</MenuItem>
    <MenuItem value={20}>Twenty</MenuItem>
    <MenuItem value={30}>Thirty</MenuItem>
  </Select>
);

return (
  <RHFInput
     as={<WrappedSelect />}
     name="CountryId"
     register={register}
     setValue={setValue}
     variant="outlined"
     margin="normal" // bunch of material-ui Select props
  />
);
```   

And I couldn't figure out why `variant`, `margin`, `value`, etc. weren't getting applied to the `Select` (material-ui was complaining about trying to set the value to undefined on the `Select`).   The problem was if you use a wrapper, RHFInput is actually cloning the wrapper element (`WrappedSelect`) and it is getting the props passed down to it.  So you need to forward those props that are coming in to the _real_ `Select` element in that case by passing the props down:

```javascript
const WrappedSelect = (propsFromRHFInputImNowForwarding) => (
  <Select {...propsFromRHFInputImNowForwarding}>
    <MenuItem value={10}>Ten</MenuItem>
    <MenuItem value={20}>Twenty</MenuItem>
    <MenuItem value={30}>Thirty</MenuItem>
  </Select>
);
```

**Comment by bluebill1049** [comment]
sorry for the late reply. i do spread rest of the props to the `as` component

```
return React.cloneElement(as, {
      ...(onChangeEvent
        ? {
            [onChangeName || 'onChange']: eventWrapper(
              onChangeEvent,
              'onChange',
            ),
          }
        : { onChange: handleChange }),
      ...(isOnBlur
        ? onBlurEvent
          ? { [onBlurName || 'onBlur']: eventWrapper(onBlurEvent, 'onBlur') }
          : { onBlur: handleBlur }
        : {}),
      value: value || inputValue,
      ...(isCheckbox ? { checked: inputValue } : {}),
      ...rest,
    });
```

i am going to close this issue now, feel free to leave more questions and suggestions tho. 👍
