### ISSUE TITLE
setValue and register props are not optional when inside FormContext

### ISSUE THREAD

**Issue by RiccardoCampitelli** [react-hook-form/react-hook-form-input#13]
Hey there,

I am implementing RHFInput in a typescript project.

I'm not sure if i am making a mistake in my code somewhere but I am trying to use RHFInput like this:

![image](https://user-images.githubusercontent.com/43190673/69969660-bea16980-1514-11ea-9648-9f74dce7fd5d.png)

but I get an error telling me that they are both required.

Am i using this wrong? if not can i submit a PR?

P.S. Love your library, great work  👍.

**Comment by bluebill1049** [comment]
you are right :) please submit a PR ❤️ and thank you :)
