### ISSUE TITLE
Using react-number-format floatValue

### ISSUE THREAD

**Issue by matiushariman** [react-hook-form/react-hook-form-input#14]
**Describe the question?**
Can we actually use react-number-format floatValue as the value of RHF field? The reason is because it will be very useful for validation

At the moment I can only get RHF working with formattedValue of RNF.

**To Reproduce**
1. Implement react-number-format on top of RHF
2. Type some numbers
3. See RHF actually gets RNF formattedValue instead of floatValue

**Codesandbox link**
https://codesandbox.io/s/boring-johnson-crxsz?fontsize=14&hidenavigation=1&theme=dark

**Screenshots**
https://imgur.com/alUU1yH

**Additional context**
By default, RNF onValueChange returns an object in following format:
`
{
      formattedValue: '$23,234,235.56', 
      value: '23234235.56', 
      floatValue: 23234235.56 
}`

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-number-format-x58pw

**Comment by matiushariman** [comment]
thanks @bluebill1049 , that's what I was looking for.

big fan of RHF by the way, I will close this. Thanks!

**Comment by bluebill1049** [comment]
No worries @matiushariman thanks mate :)

**Comment by matiushariman** [comment]
@bluebill1049 my bad, just one more Q if you don't mind.
Possible to do onChange validation with RHFI? 
As per docs I believe we can set **mode** as **onChange** in either one or both useForm and RHFInput levels. But that does not seem to trigger the validation when changing the value of RHFInput 

https://codesandbox.io/embed/react-hook-form-number-format-1g8p1

**Comment by bluebill1049** [comment]
I will take a look at it :)

**Comment by matiushariman** [comment]
@bluebill1049 thanks!

**Comment by bluebill1049** [comment]
hey @matiushariman the next patch will solve this problem.

https://codesandbox.io/s/react-2igx7

**Comment by matiushariman** [comment]
awesome, will be waiting for that @bluebill1049 . Thanks!

**Comment by bluebill1049** [comment]
it's released :) let me know how it goes.

**Comment by matiushariman** [comment]
@bluebill1049 yup, it works. Thanks

I notice another thing. Seems like while using RHFI in **onChange** mode, input change won't affect RHF formState at all. It will be triggered only on submit.
The issue is there is no way to track the changes in formState (dirty, touched, etc) when changing the value.

Wondering if you're purposely doing it, and if there's any workaround for that.

**Comment by bluebill1049** [comment]
looks like it's a bug. you have a codesandbox for this?

**Comment by bluebill1049** [comment]
also asking a favor here, if you find RHF is useful. please consider leave us a star to support :)

**Comment by matiushariman** [comment]
OK, strange that it works on the codesandbox but not in my project. Perhaps due to version differences or some bugs in my app. I'll double check ASAP. 
https://codesandbox.io/s/react-bb21n

Sure, star it is. :)

**Comment by bluebill1049** [comment]
thanks @matiushariman maybe try to get the latest version for both RHF and RHFInput. see if that solves the problem.

**Comment by bluebill1049** [comment]
thanks a lot of the star, could you please star the main repo https://github.com/react-hook-form/react-hook-form? I am hoping RHF can get more popular, while RHFInput is a support package :) sorry I didn't make it clear 👍

**Comment by matiushariman** [comment]
@bluebill1049 done.

Just to update you, I can confirm that upgrading to the latest release solve the formState issue. 
And sorry for being off topic, what do you think is the best way to do on mount validation? So far I use a custom register to do it (passing a callback func to validate)

https://react-hook-form.com/api#register

```
<input
  name="test"
  ref={
    register({
      validate: value => value === '1'
    })
  }
/>
```

**Comment by bluebill1049** [comment]
what do you mean onmount validation?

**Comment by bluebill1049** [comment]
guess we can close this issue, we can continue the conversation in here anyhow

**Comment by bluebill1049** [comment]
by the way if you have other questions, feel free to join our spectrum channel. sometimes even the community can answer your questions :) (and i am in there too).

**Comment by matiushariman** [comment]
for sure @bluebill1049 , I'm already inside the channel actually.

Looking forward to discussing more & potentially helping you guys out. Thanks again :)
