### ISSUE TITLE
Usage with Baseweb

### ISSUE THREAD

**Issue by mrtnbroder** [react-hook-form/react-hook-form-input#16]
We are using [baseweb](baseweb.design) as our go-to component-library at work. It's a library baked by Uber and under active development and growing.

I'd like to have more examples added to react-hook-form (or react-hook-form-input) on how these two libraries can work together. In general they work pretty well together out of the box, but as soon as you have more advanced stuff (dynamic and nested forms) it's getting quite complex. (take a look at the `<Select/>` component, which takes an object as it's value instead of a simple string).

Maybe someone of the core react-hook-form members can take a look at baseweb and create some arbitrary examples on how it can work with react-hook-form? I can also setup a PR.

**Comment by mrtnbroder** [comment]
Sounds like a good idea, thank you so much @bluebill1049 !

**Comment by JeromeDeLeon** [comment]
@mrtnbroder Do you mind sharing your use case through codesandbox? I'd like to take a look at it as well as I am curious on how does this wrapper works with other UI lib. Many Thanks!

**Comment by JeromeDeLeon** [comment]
I was using `react-hook-form` using Semantic UI before it got to this point. I haven't tried updating my code to use this lib. I'd like to see how far can this wrapper go in terms of forms complexity. :smiley:

**Comment by mrtnbroder** [comment]
Hi @JeromeDeLeon 
sure thing, I already had one on my codesandbox: https://codesandbox.io/s/select-2h59w
where I was playing around with the select field from baseweb.
Please notice that I am actually using an **older** version of `react-hook-form-input` as the new one wasn't working for me anymore with baseweb. It never really set the value (which it does in my codesandbox. Give it a try and update to the latest version of `react-form-hook-input` in my codesandbox and see it break).

(And please ignore that I am actually calling the instance `formik` 😅 😄 😄)

**Comment by bluebill1049** [comment]
here is my version: https://codesandbox.io/s/select-p2t67

**Comment by mrtnbroder** [comment]
@bluebill1049 your example is broken? I mean, you set a a default value but it clearly isn't set. I wouldn't close this issue until it's solved.

**Comment by bluebill1049** [comment]
I posted my reply without any feedback, so I thought you have moved on with this issue...

**Comment by bluebill1049** [comment]
what's the issue with the default value?

**Comment by mrtnbroder** [comment]
You gave RHInput the name of `test` but it should be `color`. If you set it to color the value shown inside the select will be blank. It should show `Aqua`. Makes sense?

**Comment by bluebill1049** [comment]
is `make sense` necessary? my demo was trying to show you there is `onChangeEvent`.

**Comment by bluebill1049** [comment]
I am more than happy to help issues around and that's why doing open source, but it should respectful the way we communicate with each other.

**Comment by mrtnbroder** [comment]
Not sure I understand, I wasn't trying to be rude. I just wanted to make sure you get what I meant.

I get there is `onChangeEvent`. The problem now is with the `defaultValue`. In your example, `defaultValues: { color: options[2] }` is not picked up by `<Select/>` it looks like.

my apologies if it sounded rude!

**Comment by bluebill1049** [comment]
I am looking into a solution right now, I get the issue with default value not selected. 

The original demo was trying to fix the way it was implemented by using `onChangeEvent`.

**Comment by mrtnbroder** [comment]
@bluebill1049 thanks a bunch. Again, my apologies if I sounded rude! 🌹

**Comment by bluebill1049** [comment]
apologize for closing the issue without follow up a message too.

**Comment by bluebill1049** [comment]
strange it actually works with `value`

```
<RHFInput
        name="test"
        setValue={setValue}
        register={register}
        onChangeEvent={onChange}
        value={{ label: "AliceBlue", id: "#F0F8FF" }}
        as={
          <Select
            options={[
              { label: "AliceBlue", id: "#F0F8FF" },
              { label: "AntiqueWhite", id: "#FAEBD7" },
              { label: "Aqua", id: "#00FFFF" },
              { label: "Aquamarine", id: "#7FFFD4" },
              { label: "Azure", id: "#F0FFFF" },
              { label: "Beige", id: "#F5F5DC" }
            ]}
            placeholder="Select color"
          />
        }
      />
```

**Comment by mrtnbroder** [comment]
This seems to do the trick:

```typescript
const { setValue, handleSubmit, register } = useForm({
    defaultValues: {
      color: options[2]
    }
  });

  const onSubmit = body => console.log(body);

  const onChange = args => {
    return {
      value: args[0].value[0]
    };
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <RHFInput
        name="color"
        setValue={setValue}
        register={register}
        onChangeEvent={onChange}
        as={
          <Select
            options={[
              { label: "AliceBlue", id: "#F0F8FF" },
              { label: "AntiqueWhite", id: "#FAEBD7" },
              { label: "Aqua", id: "#00FFFF" },
              { label: "Aquamarine", id: "#7FFFD4" },
              { label: "Azure", id: "#F0FFFF" },
              { label: "Beige", id: "#F5F5DC" }
            ]}
            placeholder="Select color"
          />
        }
      />
      <button>Submit</button>
    </form>
  );
```

**Comment by bluebill1049** [comment]
> This seems to do the trick:
> 
> ```ts
> const { setValue, handleSubmit, register } = useForm({
>     defaultValues: {
>       color: options[2]
>     }
>   });
> 
>   const onSubmit = body => console.log(body);
> 
>   const onChange = args => {
>     return {
>       value: args[0].value[0]
>     };
>   };
> 
>   return (
>     <form onSubmit={handleSubmit(onSubmit)}>
>       <RHFInput
>         name="color"
>         setValue={setValue}
>         register={register}
>         onChangeEvent={onChange}
>         as={
>           <Select
>             options={[
>               { label: "AliceBlue", id: "#F0F8FF" },
>               { label: "AntiqueWhite", id: "#FAEBD7" },
>               { label: "Aqua", id: "#00FFFF" },
>               { label: "Aquamarine", id: "#7FFFD4" },
>               { label: "Azure", id: "#F0FFFF" },
>               { label: "Beige", id: "#F5F5DC" }
>             ]}
>             placeholder="Select color"
>           />
>         }
>       />
>       <button>Submit</button>
>     </form>
>   );
> ```

nice, i am testing

**Comment by bluebill1049** [comment]
wow it actually works!

**Comment by mrtnbroder** [comment]
Final result: https://codesandbox.io/s/select-2h59w

**Comment by bluebill1049** [comment]
awesome! thanks for sharing the fix too.

**Comment by bluebill1049** [comment]
hey @mrtnbroder is there any other components you having issue with?

**Comment by mrtnbroder** [comment]
I think that was it, I will respond again if I find anything. I'm gonna close the ticket for now 😺

**Comment by bluebill1049** [comment]
awesome thanks @mrtnbroder
