### ISSUE TITLE
react-hook-form-input + AntD Datepicker

### ISSUE THREAD

**Issue by gabrieldaghetti** [react-hook-form/react-hook-form-input#17]
I'm trying to use AntD Datepicker with RHFInput but it's not working.  I received this error on console:
![Error](https://user-images.githubusercontent.com/51544861/70048794-e989cd00-15a9-11ea-9c00-591d69fff287.PNG)

Here is my code:
![Field](https://user-images.githubusercontent.com/51544861/70048897-2786f100-15aa-11ea-9153-d96711b62ff4.PNG)

**Comment by bluebill1049** [comment]
can you provide a codesandbox?

**Comment by JeromeDeLeon** [comment]
I don't think it's related to this lib though based on your screenshots.

**Comment by JeromeDeLeon** [comment]
The problem lies on how AntD expects the value/defaultValue to be a `moment` object, however, we set the initial value of empty string in case it is `undefined`.

**Comment by JeromeDeLeon** [comment]
For now, you will need switch to manual get/set scenario where you have your own `onChangeEvent` and `value` state to track the value.

**Comment by JeromeDeLeon** [comment]
You can actually solve it by passing `null` on `defaultValue` prop.

**Comment by gabrieldaghetti** [comment]
Thank you so much!!

**Comment by dalthonmh** [comment]
Where comes RHFInput, please could you share it on codesandox please? :pray:

**Comment by bluebill1049** [comment]
> Where comes RHFInput, please could you share it on codesandox please? 🙏

That's `Controller`: https://react-hook-form.com/api#Controller

CSB: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r
