### ISSUE TITLE
Get input ref with uncontrolled form

### ISSUE THREAD

**Issue by fjuriolli** [react-hook-form/react-hook-form-input#19]
Sandbox below:
https://codesandbox.io/s/react-79dbg?fontsize=14&hidenavigation=1&theme=dark

The code from sandbox I have a simple uncontrolled form but I need to show the input somewhere else, like this with a controlled form:

```
const [name, setName] = useState('')

<input
    name="name"
    variant="outlined"
    placeholder="Please type the channel name"
    value={name}
    ref={register}
    onChange={e => setName(e.target.value)}
/>

<span>This is a {name}</span>
```

What is the most recommended way to do this with a uncontrolled form?

**Comment by bluebill1049** [comment]
Hey @fjuriolli i am not clear on what you are after in here, can you explain a bit more?

**Comment by fjuriolli** [comment]
> Hey @fjuriolli i am not clear on what you are after in here, can you explain a bit more?

Sure. In my sandbox, I have the an uncontrolled input:

```
<RHFInput
    as={<TextField placeholder="Type your first name" fullWidth={true} />}
    style={{ marginBottom: "15px" }}
    register={register}
    setValue={setValue}
    name="firstName"
/>
```

I need to take the input value and show it on a <span> for example, like this:

```<span>This is the value of the input is {inputValue}</span>```

**Comment by bluebill1049** [comment]
you can't use `watch` api?

**Comment by fjuriolli** [comment]
> you can't use `watch` api?

Is there a simple way to achieve this?

Please, take a look below:
https://codesandbox.io/s/react-09mub?fontsize=14&hidenavigation=1&theme=dark

This is what I need to do, but the code is not quite right, because TextField is not registered and if I click submit I get a empty object. To register my TextField, I need to wrap him with a RHFInput.

Is there a simpler way to the input from the code above get gathered for submitting without wrap him?

**Comment by fjuriolli** [comment]
> you can't use `watch` api?

Silly me, I just needed to add inputRef={register} to my TextField
