### ISSUE TITLE
RHFInput + Semantic UI Select / Checkbox

### ISSUE THREAD

**Issue by njuro** [react-hook-form/react-hook-form-input#21]
Hello, first of all thanks for your effort creating this library.

Today I have been trying to integrate RHF with components from Semantic UI react library. RHFInput works fine with Form.Input (basic text field), but it fails when I try to wrap Form.Select (https://react.semantic-ui.com/addons/select/) or Form.Checkbox (https://react.semantic-ui.com/modules/checkbox/) with it. I think the reason for this is that Form.Select is not implemented with traditional `<select>` html element, but rather with some `<div>` magic and Form.Checkbox also generates some strange "hidden" `<input type="checkbox">` element. I believe Semantic UI is fairly popular and used library, so I think it might be worthy to look into this, thank you! Here is the simplified code I am using, nothing is sent when the form is submitted:

```js
<Form onSubmit={handleSubmit(onSubmit)}>
  <RHFInput
    name="color"
    as={
      <Form.Select
        label="Pick a color"
        options={colors}
        required
      />
    }
    register={register}
    setValue={setValue}
  />
  <RHFInput
    name="tos"
    as={<Form.Checkbox label="Accept TOS" />}
    type="checkbox"
    register={register}
    setValue={setValue}
  />
  <Form.Button fluid>Submit</Form.Button>
</Form>
```

EDIT:

The checkbox generates following error: `_options$0$ref.attributes is undefined` and also warning `Warning: Failed prop type: Invalid prop `value` supplied to `Checkbox`. 

And the select generates no error, but the value after submitting is always undefined.

**Comment by JeromeDeLeon** [comment]
Can you generate a codesandbox for this one? Thanks.

**Comment by bluebill1049** [comment]
@njuro are you using the latest version?

**Comment by JeromeDeLeon** [comment]
I replicated your issue and led me to `react-hook-form` using my build though.

**Comment by njuro** [comment]
Here is the CSB: https://codesandbox.io/s/suspicious-frog-75c77

RHF is aware of the fields, but they are always undefined.

Looks like `react-hook-form-input` version 1.1.5 solved the error thrown by checkbox, but the value is still not there

**Comment by raymond-ong** [comment]
I think I am encountering the same issue with Semantic UI Dropdown.
Also, notice from @njuro 's CSB, you need to click the checkbox 2 times for it to get ticked.
For the Dropdown case, nothing happens the first time the user selects something. Only the second attempt selects something from the Dropdown. 
Regardless, I'm getting "undefined" inside the submit function.
Please advice. Thank you!

**Comment by bluebill1049** [comment]
Thanks I will investigate the issue soon, in the meantime you could leverage custom register at useffect. React hook from input just some sugar syntax on top. Oh and please provide a codesandbox if u can.

**Comment by JeromeDeLeon** [comment]
I think the problem lies in how we get the value from `onChange` and `onBlur` event because SUI passes the value to second param `onChange(e, props)` like so that's why `data` is always `undefined` because it only checked the `e` where the value is in the second param or maybe we can move that in [state](https://react.semantic-ui.com/modules/checkbox/#usage-remote-control). Plus, `invalid prop "value"...` is showing when passing `value` that doesn't conform to their types (string or number).

**Comment by JeromeDeLeon** [comment]
I can think of two solutions (maybe @bluebill1049 has better idea):

1. Lift the state up and let the user pass the data:
```js
// outside RHFI component
const handleChange = (e, { checked }) => {
  return checked;
}

// inside RHFI component
const handleChange = async (...args) => {
  // onChange here is the prop to lift
  const data = await onChange(args);
  setValue(name, data, isOnChange);

  // we can remove this
  if (onChange) {
    onChange(e);
  }
};
```

2. We accept second param to accomodate SUI like what @bluebill1049  did in `react-select`
```js
const handleChange = (e, props) => {
  const data = commonTask(e && e.target ? e.target : isSUI ? props : e);
  setValue(name, data, isOnChange);
  if (onChange) {
    onChange(e);
  }
};
```

**Comment by bluebill1049** [comment]
thanks @JeromeDeLeon why not use `onChangeEvent` ? there is an example in readme for react native.

**Comment by JeromeDeLeon** [comment]
Oh! Thanks! @bluebill1049 I forgot that one.

**Comment by JeromeDeLeon** [comment]
Can we not make it asynchronous?

**Comment by JeromeDeLeon** [comment]
@njuro and @raymond-ong , I'l try to provide an example for this and let you know guys.

**Comment by bluebill1049** [comment]
> Can we not make it asynchronous?

what do you mean?

**Comment by JeromeDeLeon** [comment]
`await event(args)` something like this?

**Comment by bluebill1049** [comment]
hmm then you need async right?

**Comment by bluebill1049** [comment]
and it will always return promise and resolve

**Comment by JeromeDeLeon** [comment]
Yes we can await that one.

**Comment by JeromeDeLeon** [comment]
Anyway this is beyond the scope of the issue. we'll move this discussion in the spectrum.

**Comment by bluebill1049** [comment]
sounds good

**Comment by njuro** [comment]
@JeromeDeLeon @bluebill1049 Thanks for the hints guys, I think I figured it out: https://codesandbox.io/s/dazzling-napier-ne3e6

@raymond-ong hope it will solve your issue too

**Comment by bluebill1049** [comment]
awesome @njuro! that's what i referred above.

**Comment by njuro** [comment]
Thanks @bluebill1049  , the last thing that annoys me is the 
`Warning: Failed prop type: Invalid prop 'value' supplied to 'Checkbox'`, which shows when the page is loaded, but does not seem to affect functionality.

**Comment by bluebill1049** [comment]
we should fix it, do you have a codesandbox for it? let's patch it.

**Comment by JeromeDeLeon** [comment]
@njuro , I mentioned that case above. Sorry, I wasn't able to follow up the example.

**Comment by JeromeDeLeon** [comment]
@njuro You can solve it by passing `value` as string like `tos` or `isTos`

**Comment by raymond-ong** [comment]
> @JeromeDeLeon @bluebill1049 Thanks for the hints guys, I think I figured it out: https://codesandbox.io/s/dazzling-napier-ne3e6
> 
> @raymond-ong hope it will solve your issue too

Thanks @njuro for the codesandbox and @bluebill1049 for the onChangeEvent suggestion!
Will give it a try tomorrow :-)

**Comment by bluebill1049** [comment]
@raymond-ong no worries 👍 guys

**Comment by njuro** [comment]
Thanks @JeromeDeLeon now it works perfectly. I already created a little library in my project which wraps Semantic UI form components in RHFInput so I can work with it seamlessly, might publish it as a package once I polish it.

**Comment by JeromeDeLeon** [comment]
Might as well share it here :)

**Comment by njuro** [comment]
True, here it is https://codesandbox.io/s/dazzling-napier-ne3e6 do whatever you want with it, I don't have experience publishing npm packages :) So far it contains wrappers for TextInput, Select, Checkbox, Button and Form itself

**Comment by bluebill1049** [comment]
that's awesome @njuro share the lib in here, we can publish it in our docs website.

**Comment by bluebill1049** [comment]
closing this issue for now :) we can keep the conversation in here :)

**Comment by njuro** [comment]
I added `TextArea` component to the CSB, but I am having a hard time figuring out how to preserver the value of uploaded file - see `FileInput` component. Any ideas @JeromeDeLeon @bluebill1049 ?

**Comment by njuro** [comment]
I investigated: I can cache the event in `onChangeEvent` method just fine and then log it:
```js 
function handleChange([event]) {
    const file = event.target.files[0];
    console.log(file);
}
```
But as soon as I try to `return {value: file}` or `setValue(name, file)` I get `InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable`

I made temporary workaround by passing a callback to `FileInput` which will store the uploaded file in parent component's state but that is not optimal. Can you think of something? Thanks.

**Comment by bluebill1049** [comment]
do you have a codesandbox for this?

**Comment by njuro** [comment]
@bluebill1049 yes I added it here https://codesandbox.io/s/dazzling-napier-ne3e6 see `form/FileInput.js`

**Comment by bluebill1049** [comment]
hey @njuro, after some investigation:  you will need to use `onChangeEvent` for input file.

**Comment by njuro** [comment]
@bluebill1049 thanks, can you provide an example please? I am already using onChangeEvent in my codesandbox, but it generates said error

**Comment by bluebill1049** [comment]
oh that's right @njuro i will do it today :)

**Comment by bluebill1049** [comment]
use this :)

```
function handleChange([event]) {
    return {
      value: event.target.value
    };
  }
```

**Comment by njuro** [comment]
@bluebill1049 `event.target.value` contains only path/filename e.g. `C:/fakepath/image.jpg`, not the file content itself

**Comment by bluebill1049** [comment]
what about `e.target.files`?

**Comment by bluebill1049** [comment]
do you have reference on how semantic UI does it for onChange with input file?

**Comment by njuro** [comment]
I have no problem accessing the `File` object through `event.target.files` as I demonstrated in that CSB, I can log it to console. The issue happens when I try to assign the `File` object to value property either through `setValue` or through `return { value: file }`

**Comment by bluebill1049** [comment]
how does semantic UI handle `onChange`?

**Comment by bluebill1049** [comment]
worse case you may have to 

```
function handleChange([event]) {
   setValue() // you probably already doing that
    return {
      value: event.target.value
    };
  }
```

**Comment by njuro** [comment]
@bluebill1049 Yeah, that's probably the best approach now. Closing this, thanks for you effort :)

**Comment by bluebill1049** [comment]
my pleasure :) @njuro 🙏

**Comment by alexfertel** [comment]
@bluebill1049  I have the same issue. Is there any way to solve this? I cannot use `setValue` in the `onChange` event of a raw input. I also tried `onChageEvent` with no luck.

**Comment by bluebill1049** [comment]
> @bluebill1049 I have the same issue. Is there any way to solve this? I cannot use `setValue` in the `onChange` event of a raw input. I also tried `onChageEvent` with no luck.

Could you please share a codesandbox? also why you probably should consider to use Controller as this component is no longer maintained.

**Comment by alexfertel** [comment]
@bluebill1049 Sorry, I had the following misconception: inputs with a type of file can be controlled, which was cleared by the [reactjs](https://reactjs.org/docs/uncontrolled-components.html#the-file-input-tag) docs.

> In React, an `<input type="file" />` is always an uncontrolled component because its value can only be set by a user, and not programmatically.

I was trying to solve a problem the wrong way. I just used a hidden input (`<input type="hidden" {...} />`) and that was it :grin: 

Thank you for this great library and for the quick response! Have a good weekend!

**Comment by bluebill1049** [comment]
> @bluebill1049 Sorry, I had the following misconception: inputs with a type of file can be controlled, which was cleared by the [reactjs](https://reactjs.org/docs/uncontrolled-components.html#the-file-input-tag) docs.
> 
> > In React, an `<input type="file" />` is always an uncontrolled component because its value can only be set by a user, and not programmatically.
> 
> I was trying to solve a problem the wrong way. I just used a hidden input (`<input type="hidden" {...} />`) and that was it 😁
> 
> Thank you for this great library and for the quick response! Have a good weekend!

no worries at all 👍 glad it's working out. you have a great weekend too.
