### ISSUE TITLE
Question about RHFI witrh +react-select

### ISSUE THREAD

**Issue by edouardb** [react-hook-form/react-hook-form-input#22]
Hi,

I just tried to run the Quickstart example on the readme with the latest release. It seems that the value is well updated and set but not updated in the react-select input. Is this a regression as it works fine with previous version? Thanks

https://codesandbox.io/s/suspicious-allen-0f0vy

**Comment by bluebill1049** [comment]
hey @edouardb i think i broked the component on last release. i will patch it ASAP.

**Comment by bluebill1049** [comment]
latest version should fix it now :)

**Comment by edouardb** [comment]
Awesome! 🤗
