### ISSUE TITLE
Passing and using isClearable to React-Select generates 'Cannot read property 'label' of null' 

### ISSUE THREAD

**Issue by tylern-dev** [react-hook-form/react-hook-form-input#25]
Passing and using isClearable to React-Select generates 'Cannot read property 'label' of null' .
This can also be seen in the React Hook Form Input demo on code sandbox where isClearable is being used in the RHFInput props being passed to React-Select.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-hookforminput-rzu9s

**Expected behavior**
Should be able to press the 'X' to clear the input

**Comment by bluebill1049** [comment]
thanks @tylern88
