### ISSUE TITLE
RHFInput 'onBlur' mode deselects selected option when using React-Select

### ISSUE THREAD

**Issue by tylern-dev** [react-hook-form/react-hook-form-input#27]
**Describe the question?**
First off, great work on this library and React-Hook-Form! I wanted to see if I am using this prop,
`mode='onBlur'` correctly in React-Hook-Form-Input. 

Here is my code:
```
<RHFInput
  as={<Select />}
  options={options}
  name={name}
  register={register}
  setValue={setValue}
  rules={{required: isRequired }}
  mode='onBlur'
/>
```
When I use the 'onBlur' mode, after selecting an item in the dropdown, and then go to another input, the item in the dropdown gets deselected. 
I am using the latest version of all libraries. 
I have provided an example on codesandbox.

**Codesandbox link**
https://codesandbox.io/s/friendly-cdn-4xgjm?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment]
hmm looks like with react-select `onBlur` is return different payload than `onChange`.
https://github.com/JedWatson/react-select/issues/186

**Comment by bluebill1049** [comment]
looks like you will have to trigger validation by attach `onBlur` event manually: 

```
       <RHFInput
          as={<ReactSelect />}
          options={options}
          name="ReactSelect"
          onBlur={() => {
            triggerValidation({ name: "ReactSelect" });
          }}
          isClearable
          {...methods}
        />
```

**Comment by bluebill1049** [comment]
hey @tylern88 is above solution works for you?

**Comment by tylern-dev** [comment]
@bluebill1049 thanks for the suggestion, that seemed to be what I was needing.

**Comment by bluebill1049** [comment]
awesome thanks @tylern88 closing this :)
