### ISSUE TITLE
Type error about async validate function

### ISSUE THREAD

**Issue by wizard200541** [react-hook-form/react-hook-form-input#30]
**Describe the bug**
When passing an async function to register's validate rule, there would be a type error. But dispite the type check result, js could run well.

**Additional context**
looks like same issue
https://github.com/react-hook-form/react-hook-form/issues/367

**Comment by bluebill1049** [comment]
can you provide a codesandbox?

**Comment by wizard200541** [comment]
Yes, of course. Here is the [codesandbox link.](https://codesandbox.io/s/beautiful-varahamihira-4u55d)

**Comment by bluebill1049** [comment]
fixed will be in the next patch :)
