### ISSUE TITLE
RHFInput + AntD TimePicker isn't working after 1.1.0

### ISSUE THREAD

**Issue by iamchanii** [react-hook-form/react-hook-form-input#32]
**Describe the bug**
RHFInput + AntD TimePicker is not working on `react-hook-form-input^1.1.0`.

**To Reproduce**
Try to change TimePicker value on each codesandbox.

**Codesandbox link**
- `1.0.14`: https://codesandbox.io/s/react-hook-form-antd-timepicker-1014-i1p8i
- `latest`: https://codesandbox.io/s/react-hook-form-antd-timepicker-latest-u6ot7 

**Expected behavior**
RHFInput + AntD TimePicker should be working even latest(>1.0.14)

**Screenshots**
![2019-12-13 10-11-21 2019-12-13 10_11_39](https://user-images.githubusercontent.com/26643843/70761569-fc15ba80-1d90-11ea-9dc2-4ba5ca562081.gif)

![2019-12-13 10-05-21 2019-12-13 10_06_16](https://user-images.githubusercontent.com/26643843/70761349-3fbbf480-1d90-11ea-844e-18b4ea5fc7c1.gif)

**Desktop (please complete the following information):**
 - Chrome 78 on macOS (Catalina)
 - https://whatismybrowser.com/w/X2PXWT3

**Smartphone (please complete the following information):**

**Additional context**
Tell me if is there a point what I missed! and thank you to your works.

**Comment by bluebill1049** [comment]
thanks @iamchanii i will take a look this issue over the weekend.
