### ISSUE TITLE
Using RFHInput with MaterialUI TextField : `[object HTMLInputElement]` when empty

### ISSUE THREAD

**Issue by stephoune** [react-hook-form/react-hook-form-input#33]
**Describe the bug**
When writing in TextField MaterialUI component and deleting all characters, it fills the TextField with `[object HTMLInputElement]`

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-hookforminput-rzu9s
2. Write in 'MUI TextField'
3. Delete all chars

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-hookforminput-rzu9s

**Screenshots**
![ErrorRHFInput](https://user-images.githubusercontent.com/54548333/70798180-8fa5b600-1da6-11ea-9036-73817eecb03f.gif)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [79.0.3945.79]

**Comment by bluebill1049** [comment]
thanks patching it.
