### ISSUE TITLE
Lost selected option in Select component when value is 0

### ISSUE THREAD

**Issue by cargallo** [react-hook-form/react-hook-form-input#37]
**Describe the bug**

When wrapping a Select component and in the options there is one with value 0 then the onChange event let the Select component with empty option selected.

For testing select in sandbox the Zero option in either MUI selecto or React Select (the sandbox was modified from original @bluebill1049 example)

**Codesandbox link**

https://codesandbox.io/s/react-hook-form-rhfinput-1d9yf

**Already tested things**

I already tested using only RHF without RHFInput and it works, so I supose it is a problem with RFHInput

**Comment by bluebill1049** [comment]
```
<Select>
                  <MenuItem value="0">Zero</MenuItem>
                  <MenuItem value="1">One</MenuItem>
                  <MenuItem value="2">Two</MenuItem>
                </Select>
```

use string solve the problem. the component itself is setting state correctly.

**Comment by cargallo** [comment]
@bluebill1049  I do not completly understand the RHFInput code but I think that the problem is related to the line [134](https://github.com/react-hook-form/react-hook-form-input/blob/master/src/index.tsx#L134). If inputValue (I don't understand when value is used) if the inputValue is Zero, the expression evaluate as falsy and '' is retrieved. It is loosing the value Zero as number.

```JSX 
value: inputValue || value || '',
```
https://github.com/react-hook-form/react-hook-form-input/blob/master/src/index.tsx#L134

**Proposed Solution**

It could do something like this 

```JSX
value: inputValue === 0 ? 0 : inputValue || value || ''
```
and in types.ts on line [47](https://github.com/react-hook-form/react-hook-form-input/blob/master/src/types.ts#L47) defaultValue must be type any

defaultValue?: string;

Not sure how this could affect the use of React Select

**Comment by bluebill1049** [comment]
maybe we can check `undefined`? you want to send a PR for this fix?

**Comment by bluebill1049** [comment]
I have fixed that in V4, which we will move RHFInput into RHF

```
const value = isUndefined(inputState)
    ? isUndefined(inputState)
      ? ''
      : defaultValue
    : inputState;
```
