### ISSUE TITLE
Checkbox validation is not working as expected

### ISSUE THREAD

**Issue by lazyd3v** [react-hook-form/react-hook-form-input#39]
**Describe the bug**
We have a form with checkbox. This checkbox has `required: true` validation. If checkbox is unchecked, formState.isValid should be false, but if RHFInput is used with custom checkbox, formState.isValid is true

**Codesandbox link**
If react-hook-form-input is used: https://codesandbox.io/s/upbeat-satoshi-2324v
Without react-hook-form input: https://codesandbox.io/s/intelligent-morse-2hgmf

**Expected behavior**
Submit button should be disabled if checkbox is not checked. We can see this behaviour in example without react-hook-form-input, but not in the rhfinput-powered

**Comment by lazyd3v** [comment]
It seems I found the issue, gonna create a PR :)

**Comment by bluebill1049** [comment]
OMG amazing i was looking at it. much appreciated i really need some help on this. busy working on RHF V4 at the moment. thank you 🙏

**Comment by bluebill1049** [comment]
@lazyd3v we release a fix this morning hopefully this will fix your issue

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form-input/releases/tag/v1.1.10

**Comment by lazyd3v** [comment]
@bluebill1049 No, it's not working. Please check codesandbox I provided. `formState.isValid` always return true, even if required checkbox is not checked

**Comment by bluebill1049** [comment]
thanks for validating. i am busy with the V4 stuff didn't get chance to validate myself. reason type="checkbox" will break RHF, because RHF will treat it as Input checkbox which is really not the case. as an alternative solution for now: to get your stuff working is to trigger a validation in useEffect, until i figure something out.

**Comment by bluebill1049** [comment]
I am going to apply a fix @ RHF

**Comment by bluebill1049** [comment]
plz re-verify: https://codesandbox.io/s/gifted-gates-btlkn-delete-btlkn i did test this time.

**Comment by lazyd3v** [comment]
@bluebill1049 lgtm :)

**Comment by bluebill1049** [comment]
released :)

**Comment by bison92** [comment]
Hey, this is 404
> plz re-verify: https://codesandbox.io/s/gifted-gates-btlkn-delete-btlkn i did test this time.
I'm on the same situation, google is yelding only results about multiple checkboxes and there's no example of a simple checkbox required to be checked.
