### ISSUE TITLE
AntD switch is not correctly if type is checkbox.

### ISSUE THREAD

**Issue by iamchanii** [react-hook-form/react-hook-form-input#41]
**Describe the bug**
When I use Antd switch with RHFInput, I think it is right to set type to `checkbox`. then, Switch is not working. but if type is `input`, it is working.

**To Reproduce**
Checkout below codesandbox.

**Codesandbox link**
https://codesandbox.io/s/rhf-input-with-antd-switch-2rdwx

**Expected behavior**
It should be work with `type="checkbox"` not `type="input"`

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome 78 on catalina

**Smartphone (please complete the following information):**

**Additional context**
I think it is a bug. so I will create a PR for resolve this issue. can I?

**Comment by iamchanii** [comment]
As I inspected, getValue should be check `target.checked` is undefined or not.

**Comment by bluebill1049** [comment]
want to spend a PR for this @iamchanii ?

**Comment by iamchanii** [comment]
If I can, YES!

**Comment by bluebill1049** [comment]
lovely thank you
