### ISSUE TITLE
React Semantic UI modal with React Hook Form default values disappear

### ISSUE THREAD

**Issue by hanrok** [react-hook-form/react-hook-form-input#44]
Hi,

I'm trying to create an edit user modal that gets default values of the user details from outside of the component.
The modal is written using React-Semantic-UI and triggered by "edit button". The issue is that when I exit and re-enter to the modal the default values of the form are disappear

**To Reproduce**
1. Go to this sandbox
2. Click on Edit User
3. Exit from modal by ESC or clicking outside the modal
4. Enter again
5. see the Full-Name field disappear

**Codesandbox link**
https://codesandbox.io/s/react-semantic-ui-react-form-hook-issue-ckyt8?fontsize=14&hidenavigation=1&theme=dark

I think the issue is that the `input` tag is recreated every time I enter the modal again but the form reference still to the old one.

Do you have any idea how can I solve this issue?

Thanks a lot!

**Comment by bluebill1049** [comment]
ok figure it out, https://codesandbox.io/s/react-semantic-ui-react-form-hook-issue-evldk you are missing unregister, because component get unmounted.

**Comment by hanrok** [comment]
Sorry if I didn't get it right but where should the unregister action need to take place?
I'm registering items only on the JSX tags so I thought the `unregister` would fire automatically when the tags are purged.

Where do I need to move the unregister call? do I need to iterate over all fields on component unmount?

Thanks a lot

**Comment by bluebill1049** [comment]
@hanrok you saw my codesandbox works right?

you are just missing pass down the props :) 
`<RHFInput unregister={unregister} />`

**Comment by hanrok** [comment]
You are right, it's work! thanks!
Love this library. Maybe it will be nice to add this to the documentation because I didn't find it myself.

Thank you again 👍 😄

**Comment by bluebill1049** [comment]
actually you want to contribute to
<img width="899" alt="Screen Shot 2019-12-18 at 7 21 05 am" src="https://user-images.githubusercontent.com/10513364/71031206-07892d00-2167-11ea-9430-fa3e7b1d1b32.png">
 the readme? to do a simple description?
