### ISSUE TITLE
RHF Input with React-Select Libary

### ISSUE THREAD

**Issue by visualroam** [react-hook-form/react-hook-form-input#49]
Hey,

when working with the RHF Input Libary and Select, the option I select is not being selected. And does not show up at the submition.

>     "react": "^16.12.0",
>     "react-hook-form": "^3.28.12",
>     "react-hook-form-input": "^1.1.3",

`<RHFInput as={<Select
                                                        width='100%'
                                                        placeholder="Wunschhändler"
                                                        options={sales}
                                                    />}
                                                              setValue={setValue}
                                                              name={"whish_market"}
                                                              id={"whish_market"}
                                                              register={register}/>`

I tried it exactly like the quick start example.

**Comment by cfnelson** [comment]
@visualroam This pkg has been merged into the main lib and is now called `Controller`. See link -> https://react-hook-form.com/api#Controller

**Comment by bluebill1049** [comment]
thanks @cfnelson yes please use Controller instead.
