### ISSUE TITLE
Doesn't unregister fields

### ISSUE THREAD

**Issue by GProst** [react-hook-form/react-hook-form-input#5]
Sandbox example:
https://codesandbox.io/s/doesnt-unregister-h3sf4

Click submit to see that fields of the removed fields are still present. I believe `unregister` method inside `RHFInput` is `undefined`.

**Comment by GProst** [comment]
@bluebill1049 I'm afraid this didn't fix it =(
Unfortunately, having problem of updating react-hook-form version in the Sandbox above but locally in my project it still doesn't unregister fields for me... Double-checked that version is `3.28.5`, removed/installed node_modules from scratch just in case - didn't help

**Comment by bluebill1049** [comment]
oh really? what's `register` return?

**Comment by bluebill1049** [comment]
still return undefined?

**Comment by GProst** [comment]
@bluebill1049 
```js
ƒ () {
    return unregister(name);
}
```
but the fields are still passed to the `onSubmit` handler...

**Comment by bluebill1049** [comment]
```
    if (validationOptions && isString(validationOptions.name)) {
      registerIntoFieldsRef(
        { name: validationOptions.name },
        validationOptions,
      );
      return () => unregister(name);
    }
```

**Comment by bluebill1049** [comment]
code i have in RHF

**Comment by bluebill1049** [comment]
sorry i know why now!

**Comment by GProst** [comment]
@bluebill1049 no worries!

**Comment by bluebill1049** [comment]
try this beta: react-hook-form@3.28.6-beta.1
i will do proper fix today

**Comment by GProst** [comment]
@bluebill1049 I'm not sure why but some of my inputs stopped updating values at all, like I'm typing and nothings fills. I see that `handleChange` method is invoked, `name` seems to be correct and `data` too but the `value` is `undefined` anyway during the next render.
Interestingly that this happens to some fields, not sure I understand how they are different...

react-hook-form@3.28.6-beta.1

I was talking about `handleChange` in `RHFInput`

**Comment by GProst** [comment]
Perhaps this is something on my side, trying to debug, but all I did was updating a lib

**Comment by GProst** [comment]
Reverted to 3.28.5 and fields started to work again.

@bluebill1049 I found why some fields work okay and some don't work.
Fields work normally if they don't have default values provided to `useForm` (3.28.6-beta.1)

**Comment by bluebill1049** [comment]
I will test more on this feature today and get a proper fix. Idea is you don’t need to pass unregistef let register return it

**Comment by bluebill1049** [comment]
looks like this version works: https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-l19pz

**Comment by GProst** [comment]
@bluebill1049 
If you set some default values to `useForm` you won't be able to update a field:
https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-oh0jl

**Comment by bluebill1049** [comment]
ok i see

**Comment by bluebill1049** [comment]
working one: https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-to-delete-elloq
i will have publish both libs :)

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-l19pz works now going to publish both FYI
