### ISSUE TITLE
export 'useFormContext' was not found in 'react-hook-form'

### ISSUE THREAD

**Issue by yelvert** [react-hook-form/react-hook-form-input#50]
Receiving the following error when importing from `react-hook-form-input/dist/index.es.js`. I'm using `import { FormContext, useForm } from 'react-hook-form/dist/react-hook-form.es'` in my application.
```
ERROR in ./node_modules/react-hook-form-input/dist/index.es.js 95:16-30
"export 'useFormContext' was not found in 'react-hook-form'
```

If I manually change line 2 of `node_modules/react-hook-form-input/dist/index.es.js` to `import { useFormContext } from 'react-hook-form/dist/react-hook-form.es';`, it works fine.

I'm using webpack and typescript with ts-loader.
My tsconfig.json file:
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "lib": ["es6", "dom"],
    "module": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "jsx": "react",
    "baseUrl": ".",
    "paths": {
      "@ui/*": ["app/javascript/packs/ui/*"],
      "*": ["node_modules/*", "app/javascript/*"]
    }
  },
  "exclude": [
    "**/*.spec.ts",
    "node_modules",
    "vendor",
    "public"
  ],
  "compileOnSave": false
}
```

**Comment by bluebill1049** [comment]
This component is for V3, you are using V4 and Controller is the one you are. :)
