### ISSUE TITLE
RHFInput + Semantic UI (Checkbox and Select)

### ISSUE THREAD

**Issue by eduardocp** [react-hook-form/react-hook-form-input#53]
Hello! First of all, thenks for the lib!

I didn't want to reopen an old issue that already exists here because it was solved at the time (#21 ).

Updating the versions of the libs involved in the mentioned sandbox, again we have an incompatibility.

Am I doing it wrong or is it really a bug?

The updated sandbox is: https://codesandbox.io/s/musing-rubin-se6t8

**Comment by bluebill1049** [comment]
hey @eduardocp you probably should start using `Controller` from v4.

https://react-hook-form.com/api#Controller
