### ISSUE TITLE
Cursor AutoFocus to the end on editing text

### ISSUE THREAD

**Issue by pritishvaidya** [react-hook-form/react-hook-form-input#54]
**Describe the bug**
The cursor to add /  edit the text  is automatically  shifting to the end on any operation performed

**To Reproduce**
1. Go to the First Name field in the CodeSandBox link
2. Type in any text
3. Delete any text in the middle

**Codesandbox link**
https://codesandbox.io/s/react-native-hooks-form-testing-723e0

**Expected behavior**
The cursor should remain in the same position

**Screenshots**
No Screenshots

**Desktop (please complete the following information):**
 - Any Browser 
 - Latest Version

**Comment by bluebill1049** [comment]
plz use controller. it's part of the core lib now.
