### ISSUE TITLE
Inputs don't update if `rules` prop is provided

### ISSUE THREAD

**Issue by GProst** [react-hook-form/react-hook-form-input#7]
CodeSandbox example:
https://codesandbox.io/s/doesnt-unregister-uoj4g

Steps to reproduce:
1. Set default value to `useForm`
2. Pass `rules` prop to `RHFInput` (so that it's a new object each new render)
3. Each re-render the new `rules` object will be passed to `RHFInput` and it will trigger `unregister` method. For example, I access `formState.dirty` prop and it gets re-rendered each time a user types

**Comment by bluebill1049** [comment]
hmmm maybe we should remove rules in the dep

**Comment by GProst** [comment]
@bluebill1049 yeah, I thought the same

**Comment by GProst** [comment]
@bluebill1049 will it be simpler to not provide deps there at all and unregister only on unmount? If a user wants to unregister when `name` is changed or smth else is changed they can just manage it via `key` prop.

**Comment by bluebill1049** [comment]
yea let's do that, you want to send a PR for this? I am trying to fix a bug for react native with this component.

**Comment by GProst** [comment]
@bluebill1049 of course!

**Comment by bluebill1049** [comment]
thanks a lot @GProst much appreciated

**Comment by bluebill1049** [comment]
`1.0.14-beta.1` plz help test this out.

**Comment by GProst** [comment]
@bluebill1049 I think it doesn't include changes from https://github.com/react-hook-form/react-hook-form-input/pull/8

**Comment by bluebill1049** [comment]
dame...

**Comment by bluebill1049** [comment]
thought you merged it hahah

**Comment by GProst** [comment]
😆

**Comment by bluebill1049** [comment]
`1.0.14-beta.2`

**Comment by GProst** [comment]
@bluebill1049 seems to be working great now 🎉 all e2e tests in the project I'm working on passed FWIW

**Comment by bluebill1049** [comment]
lovely publishing!

**Comment by bluebill1049** [comment]
thanks a lot for your contribution. too many things in my hands it's so good to have people willing to help :) (RHF team members are helpful too) @kotarella1110 @JeromeDeLeon ❤️

**Comment by bluebill1049** [comment]
hey @GProst i am putting back `register unregister name` and only leave out rules. you ok with that?

**Comment by GProst** [comment]
@bluebill1049 I guess this won't harm

**Comment by bluebill1049** [comment]
kk thanks :)

**Comment by bluebill1049** [comment]
hey @GProst FYI when i get some more free time, i think its probably worth to make a `RHFFieldArray` to abstract those logic.

**Comment by GProst** [comment]
@bluebill1049 sounds awesome!
